---
title: "ExtractFireAtlasDetails"
author: "Anna Talucci"
date: "2025-04-28"
output: html_document
---

# Overview
years of interest: 

LC "2015" "2018" "2019" "2020" "2021" "2022"
lcc 2013 2015 2017 2018 2019 2020 2021 2022
fisl "2004" "2015" "2019" "2020" "2021"

# Packages

```{r}
library(tidyverse)  # Data manipulation & visualization
library(sf)
```

# Data

## Points
```{r}
fisl_dob_with_na = st_read("../outputs/2025-08-31_dob_na/fisl_dob_na_2025-08-31.gpkg")
lc_dob_with_na = st_read("../outputs/2025-08-31_dob_na/lc_dob_na_2025-08-31.gpkg")
lcc_dob_with_na = st_read("../outputs/2025-08-31_dob_na/lcc_dob_na_2025-08-31.gpkg")
org_dob_with_na = st_read("../outputs/2025-08-31_dob_na/org_dob_na_2025-08-31.gpkg")
```
# Check Unique Fire years

```{r}
sort(unique(fisl_dob_with_na$fireYr))
sort(unique(lc_dob_with_na$fireYr))
sort(unique(lcc_dob_with_na$fireYr))
sort(unique(org_dob_with_na$fireYr))
```

# Filter points for fire year

```{r}
points = fisl_dob_with_na
( points_subset = points %>% filter(fireYr=="2020") %>% st_transform(., crs=3571) )
```

## Fire Atlas data

```{r}
gpkg_files <- list.files("../data/fireAtlas/2020/Snapshot", pattern='.gpkg$', full.names=TRUE)
```

```{r}
first = st_read(gpkg_files[1])
first
```





# Function to read one gpkg and spatial join to points

```{r}
join_one <- function(file) {
  poly <- tryCatch(st_read(file, quiet = TRUE), error = function(e) return(NULL))
  if (is.null(poly) || nrow(poly) == 0) return(NULL)

  if (st_crs(poly) != st_crs(points_subset)) {
    poly <- st_transform(poly, st_crs(points_subset))
  }

  joined <- st_join(points_subset, poly, join = st_intersects)

  # Force avgspread to numeric, or use mutate(across(...)) for multiple columns
  if ("avgspread" %in% names(joined)) {
    joined <- joined %>%
  mutate(across(c(avgspread, spread95, mergedate), ~ suppressWarnings(as.numeric(.))))
  }

  joined$source_file <- basename(file)
  return(joined)
}

# Map safely and drop NULLs
joined_list <- map(gpkg_files, join_one) %>%
  compact()  # removes NULL entries

# Combine
joined_points <- bind_rows(joined_list)
```

```{r}
joined_points
```

```{r}
( joined_dropna = joined_points %>% drop_na(tst_year, tst_month, tst_day) )
```

# select one point per site based on min dob

```{r}
( joined_points_min_dob <- joined_points %>%
  group_by(ID) %>%
  slice_min(ted_doy, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
    dplyr::select(ID:fireYr, tst_year, tst_month, tst_day, ted_year, ted_month, ted_day, ted_ampm, ted_doy)
)

```

```{r eval=FALSE, include=FALSE}
st_write(joined_points_min_dob, "../outputs/2025-08-31_fireatlas_dob/fisl/ fireAtlas_dob_2020.shp", driver="ESRI Shapefile")
```
