---
title: "Organize FWI and GFWED"
author: "Anna Talucci"
date: "2025-06-11"
output: html_document
---

```{r clear environment, include=FALSE}
rm(list=ls())
```

# Overview

Combine spatial data in to single dataframe


color help
http://vrl.cs.brown.edu/color

# Packages

```{r}
library(tidyverse)
```


# Data

## FWI
```{r}
fisl_fwi_list = list.files(path="../data/fisl_fwi", pattern='*.csv', full.names = TRUE)
fisl_fwi_list
```

```{r}
lc_fwi_list = list.files(path="../data/lc_fwi", pattern='*.csv', full.names = TRUE)
lc_fwi_list
```

```{r}
lcc_fwi_list = list.files(path="../data/lcc_fwi", pattern='*.csv', full.names = TRUE)
lcc_fwi_list
```

```{r}
org_fwi_list = list.files(path="../data/org_fwi", pattern='*.csv', full.names = TRUE)
org_fwi_list
```

## GFWED

```{r}
fisl_gfwed_list = list.files(path="../data/fisl_gfwed", pattern='*.csv', full.names = TRUE)
fisl_gfwed_list
```

```{r}
lc_gfwed_list = list.files(path="../data/lc_gfwed", pattern='*.csv', full.names = TRUE)
lc_gfwed_list
```

```{r}
lcc_gfwed_list = list.files(path="../data/lcc_gfwed", pattern='*.csv', full.names = TRUE)
lcc_gfwed_list
```


# Read and combine data frame list

```{r}
csv_rbind <- function(file_list) {
  csv_data <- purrr::map_dfr(file_list, read_csv)
  return(csv_data)
}

```

```{r}
(fisl_fwi = csv_rbind(fisl_fwi_list))
(lc_fwi = csv_rbind(lc_fwi_list))
(lcc_fwi = csv_rbind(lcc_fwi_list))
(org_fwi = csv_rbind(org_fwi_list))
```


```{r}
(fisl_gfwed = csv_rbind(fisl_gfwed_list))
(lc_gfwed = csv_rbind(lc_gfwed_list))
(lcc_gfwed = csv_rbind(lcc_gfwed_list))
```

# select variables

## Function

```{r}
clean_select_FWI <- function(df){df %>% 
    rename(BUI = build_up_index, DC= drought_code, DMC = duff_moisture_code, DOB_lst = dob, FFMC = fine_fuel_moisture_code, FWI = fire_weather_index, ISI = initial_fire_spread_index, DSR = fire_daily_severity_rating) %>%
  select(ID, date, DOB_lst, fireYr, BUI, DC, DMC, FFMC, FWI, ISI, DSR)
}
```

```{r}
(fisl_fwi_sub = clean_select_FWI(fisl_fwi))
(lc_fwi_sub = clean_select_FWI(lc_fwi))
(lcc_fwi_sub = clean_select_FWI(lcc_fwi))
```

```{r}
(org_fwi_sub = org_fwi%>% 
    rename(BUI = build_up_index, DC= drought_code, DMC = duff_moisture_code, FFMC = fine_fuel_moisture_code, FWI = fire_weather_index, ISI = initial_fire_spread_index, DSR = fire_daily_severity_rating) %>%
  select(id, date, DOB_lst, burn_yr, BUI, DC, DMC, FFMC, FWI, ISI, DSR)
 
)
 
```
```{r}
sort(unique(org_fwi_sub$burn_yr))
```
```{r}
( fisl_gfwed_sub = fisl_gfwed %>% select(ID, rh, t, vpd, wspeed))
( lc_gfwed_sub = lc_gfwed %>% select(ID, rh, t, vpd, wspeed) )
( lcc_gfwed_sub = lcc_gfwed %>% select(ID, rh, t, vpd, wspeed) )
```

# Combine project dataframes

```{r}
fisl_dfs <- list(fisl_fwi_sub, fisl_gfwed_sub)
lc_dfs <- list(lc_fwi_sub, lc_gfwed_sub)
lcc_dfs <- list(lcc_fwi_sub, lcc_gfwed_sub)
```



```{r}
( fisl <- reduce(fisl_dfs, full_join, by = "ID") )
( lc <- reduce(lc_dfs, full_join, by = "ID") )
( lcc <- reduce(lcc_dfs, full_join, by = "ID") )
```


# Save

```{r}
write_csv(org_fwi_sub, "../outputs/2025-08-18_cleaned/csv/2025-08-18_Org_fwi.csv")
```

```{r}
write_csv(fisl, "../outputs/2025-08-18_cleaned/csv/2025-08-18_Fisl_fwi_gfwed.csv")
write_csv(lc, "../outputs/2025-08-18_cleaned/csv/2025-08-18_LC_fwi_gfwed.csv")
write_csv(lcc, "../outputs/2025-08-18_cleaned/csv/2025-08-18_LCC_fwi_gfwed.csv")
```


