---
title: "Organize Terrain Variables"
author: "Anna Talucci"
date: "2025-08-04"
output: html_document
---



```{r clear environment, include=FALSE}
rm(list=ls())
```

# Overview

Combine revised terrain metrics


color help
http://vrl.cs.brown.edu/color

# Packages

```{r}
library(tidyverse)
```


# Load csv data

```{r}
fisl = read_csv("../data/2025-08-08_combustion_layer_update/2025-09-30_LC_FISL_Site_Data/2025-10-02_TerrainMetrics_FISL.csv")
lc = read_csv("../data/2025-08-08_combustion_layer_update/2025-10-03_LC/2025-10-03_TerrainMetrics_LC.csv")
lcc = read_csv("../data/2025-08-08_combustion_layer_update/2025-08-31_terrain/staticTerrain_LCC.csv")
org = read_csv("../data/2025-08-08_combustion_layer_update/2025-08-31_terrain/staticTerrain_ORG.csv")
```

# View data frame

```{r}
fisl
lc
lcc
org
```

# Select variables of interest

```{r}
( fisl_df = fisl %>% 
    select(HLI:TRASP, aspect_rad, elevation, ruggedness:slope_rad) %>% 
    relocate(ID) )
  
( lc_df = lc %>% 
    select(HLI:TRASP, aspect_rad, elevation, ruggedness:slope_rad) %>% 
    relocate(ID) )

( lcc_df = lcc %>% 
    select(HLI:TRASP, aspect_rad, elevation, ruggedness:slope_rad) %>% 
    relocate(ID) )

( org_df = org %>% 
    select(HLI:TRASP, aspect_rad, elevation, ruggedness:slope_rad) %>% 
    relocate(ID)  )
```


## Write to CSV

```{r}
write_csv(fisl_df, "../outputs/2025-08-18_cleaned/csv/2025-10-02_FISL_Terrain.csv")
write_csv(lc_df, "../outputs/2025-08-18_cleaned/csv/2025-10-03_LC_Terrain.csv")

write_csv(lcc_df, "../outputs/2025-08-18_cleaned/csv/2025-09-22_LCC_Terrain.csv")

write_csv(org_df, "../outputs/2025-08-18_cleaned/csv/2025-09-22_ORG_Terrain.csv")
```

**THE END**
