---
title: "StandAgeProductCompare"
author: "Anna Talucci"
date: "2025-11-20"
output: html_document
---



# Overview

Produce figures for slides for LCC meeting on November 12, 2025. 


# Packages 

```{r}
library(tidyverse)
library(ggbreak)
```

# Data 

```{r}
lcc = read_csv("../outputs/LCC_cleaned/csv/2025-11-19_LCC_SpatialData.csv")
lc = read_csv("../outputs/LCC_cleaned/csv/2025-11-26_LC_site_SpatialData.csv")
```

# View Data

```{r}
lcc
lc
```

# Select Columns of interest

```{r}
( lc_sa = lc %>% dplyr::select(ID, fire, fireYr, fieldAge, computedAge, fri, fa00, fa10, fa20, fa30, fastd, faint) )

( lcc_sa = lcc %>% dplyr::select(ID, study_area, fireYr, fieldAge, computedAge, fri, fa00, fa10, fa20, fa30, fastd, faint) )
```
```{r}
( lcc_ratio = lcc_sa %>%
  mutate(
    within_FRI_field = fieldAge <= fri, # TRUE if age <= FRI
    within_FRI_computed = computedAge <= fri, # TRUE if age <= FRI
    within_FRI_fa00 = fa00 <= fri, # TRUE if age <= FRI
    ratio_field_fri = fieldAge / fri,       # relative position (1 = equal, >1 older than FRI)
    ratio_computed_fri = computedAge / fri,       # relative position (1 = equal, >1 older than FRI)
    ratio_fa00_fri = fa00 / fri       # relative position (1 = equal, >1 older than FRI)
  )
)
```

```{r}
( lc_ratio = lc_sa %>%
  mutate(
    within_FRI_field = fieldAge <= fri, # TRUE if age <= FRI
    within_FRI_computed = computedAge <= fri, # TRUE if age <= FRI
    within_FRI_fa00 = fa00 <= fri, # TRUE if age <= FRI
    ratio_field_fri = fieldAge / fri,       # relative position (1 = equal, >1 older than FRI)
    ratio_computed_fri = computedAge / fri,       # relative position (1 = equal, >1 older than FRI)
    ratio_fa00_fri = fa00 / fri       # relative position (1 = equal, >1 older than FRI)
  )
)
```

```{r}
( lcc_diff = lcc_sa %>%
  mutate(
    dif_field_computed = fieldAge -computedAge, 
    dif_field_fa00 = fieldAge -fa00, 
    dif_field_fa10 = fieldAge -fa10, 
    dif_field_fa20 = fieldAge -fa20,       
     dif_field_fa30  = fieldAge -fa30
  )
)
```

```{r}
( lc_diff = lc_sa %>%
  mutate(
    dif_field_computed = fieldAge -computedAge, 
    dif_field_fa00 = fieldAge -fa00, 
    dif_field_fa10 = fieldAge -fa10, 
    dif_field_fa20 = fieldAge -fa20,       
     dif_field_fa30  = fieldAge -fa30
  )
)
```


```{r}


( lc_ratio_plot = lc_ratio %>% 
    dplyr::select(ID:fri, ratio_field_fri:ratio_fa00_fri) %>%
    rename(field = ratio_field_fri, computed = ratio_computed_fri, fa00 = ratio_fa00_fri) %>%
    pivot_longer(
    cols = c(field, computed, fa00),
    names_to = "source",
    values_to = "ratio_age_fri")  %>%
  ggplot(aes(x = source, y = ratio_age_fri)) +
   geom_boxplot(width = 0.6, alpha = 0.2, outlier.shape = NA, color = "gray40") +
      geom_jitter(width = 0.15, alpha = 0.7, size = 1.8, shape = 21, fill=NA) +
      stat_summary(fun = mean, geom = "point", shape = 23, size = 3,
                   fill = NA, color = "firebrick2") +
  #geom_line(color = "gray70", alpha = 0.6) +  # neutral connecting line
  #geom_point(aes(color = source), size = 3) +
  facet_wrap(~ fire, scales = "free") +
  #scale_color_manual(values = c("Field" = "#1b9e77", "Computed" = "#d95f02")) +
  theme_minimal(base_size = 13) +
  labs(
    x = "",
    y = "Ratio of age to FRI",
    color = NULL
  ) +
  theme(legend.position = "none",
    strip.background = element_rect(fill = "grey90"),
    panel.grid.minor = element_blank()
  ) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        axis.title.x = element_blank()
      ) 
)
```

```{r}
ggsave(filename = "../figures/standAgeCompare/LC_boxplotFireRatioAgeFri.png", plot = lc_ratio_plot, width = 12, height = 12, dpi = 400, bg = "white" )
```


```{r}


( lcc_ratio_plot = lcc_ratio %>% 
    dplyr::select(ID:fri, ratio_field_fri:ratio_fa00_fri) %>%
    rename(field = ratio_field_fri, computed = ratio_computed_fri, fa00 = ratio_fa00_fri) %>%
    pivot_longer(
    cols = c(field, computed, fa00),
    names_to = "source",
    values_to = "ratio_age_fri")  %>%
  ggplot(aes(x = source, y = ratio_age_fri)) +
   geom_boxplot(width = 0.6, alpha = 0.2, outlier.shape = NA, color = "gray40") +
      geom_jitter(width = 0.15, alpha = 0.7, size = 1.8, shape = 21, fill=NA) +
      stat_summary(fun = mean, geom = "point", shape = 23, size = 3,
                   fill = NA, color = "firebrick2") +
  #geom_line(color = "gray70", alpha = 0.6) +  # neutral connecting line
  #geom_point(aes(color = source), size = 3) +
  facet_wrap(~ study_area, scales = "free") +
  #scale_color_manual(values = c("Field" = "#1b9e77", "Computed" = "#d95f02")) +
  theme_minimal(base_size = 13) +
  labs(
    x = "",
    y = "Ratio of age to FRI",
    color = NULL
  ) +
  theme(legend.position = "none",
    strip.background = element_rect(fill = "grey90"),
    panel.grid.minor = element_blank()
  ) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        axis.title.x = element_blank()
      ) 
)
```

```{r}
ggsave(filename = "../figures/standAgeCompare/LCC_boxplotRatioAgeFri.png", plot = lcc_ratio_plot, width = 12, height = 10, dpi = 400, bg = "white" )
```

```{r}
lc_diff
```
```{r}

summary_table_lc <- lc_diff %>%
  summarise(
    across(
      starts_with("dif_field"),
      list(
        mean   = ~ mean(.x, na.rm = TRUE),
        median = ~ median(.x, na.rm = TRUE),
        min    = ~ min(.x, na.rm = TRUE),
        max    = ~ max(.x, na.rm = TRUE)
      ),
      .names = "{.col}_{.fn}"
    )
  ) %>%
  pivot_longer(
    everything(),
    names_to  = c("variable", ".value"),
    names_sep = "_(?=[^_]+$)"   # split at last underscore: colname_stat
  ) %>%
  mutate(project = "LC-Walker")

summary_table_lc
```

```{r}

summary_table_lcc <- lcc_diff %>%
  summarise(
    across(
      starts_with("dif_field"),
      list(
        mean   = ~ mean(.x, na.rm = TRUE),
        median = ~ median(.x, na.rm = TRUE),
        min    = ~ min(.x, na.rm = TRUE),
        max    = ~ max(.x, na.rm = TRUE)
      ),
      .names = "{.col}_{.fn}"
    )
  ) %>%
  pivot_longer(
    everything(),
    names_to  = c("variable", ".value"),
    names_sep = "_(?=[^_]+$)"   # split at last underscore: colname_stat
  ) %>%
  mutate(project = "LCC")

summary_table_lcc
```

```{r}
( allSummaryTable = bind_rows(summary_table_lc, summary_table_lcc) )
```

```{r}
write.csv(allSummaryTable, "../outputs/summaryTables/2025-11-24_StandAgeDifSummaryTable.csv", row.names=F)
```

```{r}


( lc_diff_plot = lc_diff %>% 
    dplyr::select(ID:fri, dif_field_computed:dif_field_fa30) %>%
    rename(computed = dif_field_computed, fa00 = dif_field_fa00, fa10 = dif_field_fa10, fa20 = dif_field_fa20, fa30 = dif_field_fa30) %>%
    pivot_longer(
    cols = c(computed, fa00, fa10, fa20, fa30),
    names_to = "source",
    values_to = "ratio_age_fri")  %>%
  ggplot(aes(x = source, y = ratio_age_fri)) +
   geom_boxplot(width = 0.6, alpha = 0.2, outlier.shape = NA, color = "gray40") +
      geom_jitter(width = 0.15, alpha = 0.7, size = 1.8, shape = 21, fill=NA) +
      stat_summary(fun = mean, geom = "point", shape = 23, size = 3,
                   fill = NA, color = "firebrick2") +
  #geom_line(color = "gray70", alpha = 0.6) +  # neutral connecting line
  #geom_point(aes(color = source), size = 3) +
  facet_wrap(~ fire, scales = "free") +
  #scale_color_manual(values = c("Field" = "#1b9e77", "Computed" = "#d95f02")) +
  theme_minimal(base_size = 13) +
  labs(
    x = "",
    y = "Years (field age minus product age)",
    color = NULL
  ) +
  theme(legend.position = "none",
    strip.background = element_rect(fill = "grey90"),
    panel.grid.minor = element_blank()
  ) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        axis.title.x = element_blank()
      ) 
)
```

```{r}
ggsave(filename = "../figures/standAgeCompare/LC_boxplotSAProdDiff.png", plot = lc_diff_plot, width = 12, height = 12, dpi = 400, bg = "white" )
```

```{r}


( lcc_diff_plot = lcc_diff %>% 
    dplyr::select(ID:fri, dif_field_computed:dif_field_fa30) %>%
    rename(computed = dif_field_computed, fa00 = dif_field_fa00, fa10 = dif_field_fa10, fa20 = dif_field_fa20, fa30 = dif_field_fa30) %>%
    pivot_longer(
    cols = c(computed, fa00, fa10, fa20, fa30),
    names_to = "source",
    values_to = "ratio_age_fri")  %>%
  ggplot(aes(x = source, y = ratio_age_fri)) +
   geom_boxplot(width = 0.6, alpha = 0.2, outlier.shape = NA, color = "gray40") +
      geom_jitter(width = 0.15, alpha = 0.7, size = 1.8, shape = 21, fill=NA) +
      stat_summary(fun = mean, geom = "point", shape = 23, size = 3,
                   fill = NA, color = "firebrick2") +
  #geom_line(color = "gray70", alpha = 0.6) +  # neutral connecting line
  #geom_point(aes(color = source), size = 3) +
  facet_wrap(~ study_area, scales = "free") +
  #scale_color_manual(values = c("Field" = "#1b9e77", "Computed" = "#d95f02")) +
  theme_minimal(base_size = 13) +
  labs(
    x = "",
    y = "Years (field age minus product age)",
    color = NULL
  ) +
  theme(legend.position = "none",
    strip.background = element_rect(fill = "grey90"),
    panel.grid.minor = element_blank()
  ) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        axis.title.x = element_blank()
      ) 
)
```

```{r}
ggsave(filename = "../figures/standAgeCompare/LCC_boxplotSAProdDiff.png", plot = lcc_diff_plot, width = 12, height = 12, dpi = 400, bg = "white" )
```
